//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpQuantity
    {
        public int ExpId { get; set; }
        public Nullable<int> Per_Num { get; set; }
        public Nullable<int> P_Code { get; set; }
        public string Cl_Email { get; set; }
        public string St_Name { get; set; }
        public Nullable<int> Out_Quantity { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
        public virtual PerExport PerExport { get; set; }
        public virtual Store Store { get; set; }
    }
}
