//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpQuantity
    {
        public int ImpId { get; set; }
        public Nullable<int> P_Code { get; set; }
        public string Sup_Email { get; set; }
        public string St_Name { get; set; }
        public Nullable<int> In_Quantity { get; set; }
        public Nullable<System.DateTime> Transform_Date { get; set; }
        public string New_Store { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Store Store { get; set; }
    }
}
