//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Test2Entities : DbContext
    {
        public Test2Entities()
            : base("name=Test2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<PrMeasure> PrMeasures { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<PerImport> PerImports { get; set; }
        public virtual DbSet<PerExport> PerExports { get; set; }
        public virtual DbSet<ExpQuantity> ExpQuantities { get; set; }
        public virtual DbSet<stprodu> stprodus { get; set; }
        public virtual DbSet<ImpQuantity> ImpQuantities { get; set; }
    
        public virtual ObjectResult<PermitionImport_Result> PermitionImport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PermitionImport_Result>("PermitionImport");
        }
    
        public virtual ObjectResult<prodMeaser_Result> prodMeaser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prodMeaser_Result>("prodMeaser");
        }
    
        public virtual ObjectResult<proMeaser_Result> proMeaser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proMeaser_Result>("proMeaser");
        }
    
        public virtual int UpDateProduct(Nullable<int> code, string name, Nullable<System.DateTime> pDate, Nullable<System.DateTime> expDate)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var pDateParameter = pDate.HasValue ?
                new ObjectParameter("PDate", pDate) :
                new ObjectParameter("PDate", typeof(System.DateTime));
    
            var expDateParameter = expDate.HasValue ?
                new ObjectParameter("ExpDate", expDate) :
                new ObjectParameter("ExpDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpDateProduct", codeParameter, nameParameter, pDateParameter, expDateParameter);
        }
    
        public virtual int UpDateMeasure(Nullable<int> code, string name)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpDateMeasure", codeParameter, nameParameter);
        }
    
        public virtual ObjectResult<JoinTabel_Result> JoinTabel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JoinTabel_Result>("JoinTabel");
        }
    
        public virtual int UpdateTable(string storeImport, string storeExport)
        {
            var storeImportParameter = storeImport != null ?
                new ObjectParameter("storeImport", storeImport) :
                new ObjectParameter("storeImport", typeof(string));
    
            var storeExportParameter = storeExport != null ?
                new ObjectParameter("storeExport", storeExport) :
                new ObjectParameter("storeExport", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTable", storeImportParameter, storeExportParameter);
        }
    
        public virtual int InsrImq(Nullable<int> id, Nullable<int> perNum, Nullable<int> codepro, string supEmail, string stName, Nullable<int> quint)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var perNumParameter = perNum.HasValue ?
                new ObjectParameter("perNum", perNum) :
                new ObjectParameter("perNum", typeof(int));
    
            var codeproParameter = codepro.HasValue ?
                new ObjectParameter("codepro", codepro) :
                new ObjectParameter("codepro", typeof(int));
    
            var supEmailParameter = supEmail != null ?
                new ObjectParameter("supEmail", supEmail) :
                new ObjectParameter("supEmail", typeof(string));
    
            var stNameParameter = stName != null ?
                new ObjectParameter("StName", stName) :
                new ObjectParameter("StName", typeof(string));
    
            var quintParameter = quint.HasValue ?
                new ObjectParameter("quint", quint) :
                new ObjectParameter("quint", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsrImq", idParameter, perNumParameter, codeproParameter, supEmailParameter, stNameParameter, quintParameter);
        }
    
        public virtual int InsrPer(Nullable<int> perNum, Nullable<int> codepro, string supEmail, string stName, Nullable<System.DateTime> perdate, Nullable<int> qU)
        {
            var perNumParameter = perNum.HasValue ?
                new ObjectParameter("perNum", perNum) :
                new ObjectParameter("perNum", typeof(int));
    
            var codeproParameter = codepro.HasValue ?
                new ObjectParameter("codepro", codepro) :
                new ObjectParameter("codepro", typeof(int));
    
            var supEmailParameter = supEmail != null ?
                new ObjectParameter("supEmail", supEmail) :
                new ObjectParameter("supEmail", typeof(string));
    
            var stNameParameter = stName != null ?
                new ObjectParameter("StName", stName) :
                new ObjectParameter("StName", typeof(string));
    
            var perdateParameter = perdate.HasValue ?
                new ObjectParameter("perdate", perdate) :
                new ObjectParameter("perdate", typeof(System.DateTime));
    
            var qUParameter = qU.HasValue ?
                new ObjectParameter("QU", qU) :
                new ObjectParameter("QU", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsrPer", perNumParameter, codeproParameter, supEmailParameter, stNameParameter, perdateParameter, qUParameter);
        }
    
        public virtual ObjectResult<supper_Result> supper()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<supper_Result>("supper");
        }
    
        public virtual ObjectResult<disp_Result> disp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<disp_Result>("disp");
        }
    
        public virtual ObjectResult<iteamplace_Result> iteamplace(Nullable<int> pro)
        {
            var proParameter = pro.HasValue ?
                new ObjectParameter("Pro", pro) :
                new ObjectParameter("Pro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<iteamplace_Result>("iteamplace", proParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> transform(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("transform", nameParameter);
        }
    
        public virtual ObjectResult<iteam_Result> iteam(Nullable<int> pro)
        {
            var proParameter = pro.HasValue ?
                new ObjectParameter("Pro", pro) :
                new ObjectParameter("Pro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<iteam_Result>("iteam", proParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> stinfo(string st)
        {
            var stParameter = st != null ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("stinfo", stParameter);
        }
    
        public virtual ObjectResult<find_Result> find(Nullable<int> pr)
        {
            var prParameter = pr.HasValue ?
                new ObjectParameter("pr", pr) :
                new ObjectParameter("pr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<find_Result>("find", prParameter);
        }
    
        public virtual int up3(Nullable<int> id, Nullable<int> perNum, Nullable<int> codepro, string supEmail, string stName, Nullable<int> quint)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var perNumParameter = perNum.HasValue ?
                new ObjectParameter("perNum", perNum) :
                new ObjectParameter("perNum", typeof(int));
    
            var codeproParameter = codepro.HasValue ?
                new ObjectParameter("codepro", codepro) :
                new ObjectParameter("codepro", typeof(int));
    
            var supEmailParameter = supEmail != null ?
                new ObjectParameter("supEmail", supEmail) :
                new ObjectParameter("supEmail", typeof(string));
    
            var stNameParameter = stName != null ?
                new ObjectParameter("StName", stName) :
                new ObjectParameter("StName", typeof(string));
    
            var quintParameter = quint.HasValue ?
                new ObjectParameter("quint", quint) :
                new ObjectParameter("quint", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up3", idParameter, perNumParameter, codeproParameter, supEmailParameter, stNameParameter, quintParameter);
        }
    
        public virtual int upPer(Nullable<int> perNum, Nullable<int> codepro, string supEmail, string stName, Nullable<System.DateTime> perdate, Nullable<int> qu)
        {
            var perNumParameter = perNum.HasValue ?
                new ObjectParameter("perNum", perNum) :
                new ObjectParameter("perNum", typeof(int));
    
            var codeproParameter = codepro.HasValue ?
                new ObjectParameter("codepro", codepro) :
                new ObjectParameter("codepro", typeof(int));
    
            var supEmailParameter = supEmail != null ?
                new ObjectParameter("supEmail", supEmail) :
                new ObjectParameter("supEmail", typeof(string));
    
            var stNameParameter = stName != null ?
                new ObjectParameter("StName", stName) :
                new ObjectParameter("StName", typeof(string));
    
            var perdateParameter = perdate.HasValue ?
                new ObjectParameter("perdate", perdate) :
                new ObjectParameter("perdate", typeof(System.DateTime));
    
            var quParameter = qu.HasValue ?
                new ObjectParameter("Qu", qu) :
                new ObjectParameter("Qu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upPer", perNumParameter, codeproParameter, supEmailParameter, stNameParameter, perdateParameter, quParameter);
        }
    
        public virtual ObjectResult<upPer2_Result> upPer2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<upPer2_Result>("upPer2");
        }
    
        public virtual int Delet(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delet", idParameter);
        }
    
        public virtual int Delet2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delet2", idParameter);
        }
    
        public virtual int Insrexq(Nullable<int> id, Nullable<int> perNum, Nullable<int> codepro, string clEmail, string stName, Nullable<int> quint)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var perNumParameter = perNum.HasValue ?
                new ObjectParameter("perNum", perNum) :
                new ObjectParameter("perNum", typeof(int));
    
            var codeproParameter = codepro.HasValue ?
                new ObjectParameter("codepro", codepro) :
                new ObjectParameter("codepro", typeof(int));
    
            var clEmailParameter = clEmail != null ?
                new ObjectParameter("clEmail", clEmail) :
                new ObjectParameter("clEmail", typeof(string));
    
            var stNameParameter = stName != null ?
                new ObjectParameter("StName", stName) :
                new ObjectParameter("StName", typeof(string));
    
            var quintParameter = quint.HasValue ?
                new ObjectParameter("quint", quint) :
                new ObjectParameter("quint", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insrexq", idParameter, perNumParameter, codeproParameter, clEmailParameter, stNameParameter, quintParameter);
        }
    
        public virtual int perEx(Nullable<int> perNum, Nullable<int> codepro, string supEmail, string stName, Nullable<System.DateTime> perdate)
        {
            var perNumParameter = perNum.HasValue ?
                new ObjectParameter("perNum", perNum) :
                new ObjectParameter("perNum", typeof(int));
    
            var codeproParameter = codepro.HasValue ?
                new ObjectParameter("codepro", codepro) :
                new ObjectParameter("codepro", typeof(int));
    
            var supEmailParameter = supEmail != null ?
                new ObjectParameter("supEmail", supEmail) :
                new ObjectParameter("supEmail", typeof(string));
    
            var stNameParameter = stName != null ?
                new ObjectParameter("StName", stName) :
                new ObjectParameter("StName", typeof(string));
    
            var perdateParameter = perdate.HasValue ?
                new ObjectParameter("perdate", perdate) :
                new ObjectParameter("perdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("perEx", perNumParameter, codeproParameter, supEmailParameter, stNameParameter, perdateParameter);
        }
    
        public virtual int upExPer(Nullable<int> perNum, Nullable<int> codepro, string supEmail, string stName, Nullable<System.DateTime> perdate)
        {
            var perNumParameter = perNum.HasValue ?
                new ObjectParameter("perNum", perNum) :
                new ObjectParameter("perNum", typeof(int));
    
            var codeproParameter = codepro.HasValue ?
                new ObjectParameter("codepro", codepro) :
                new ObjectParameter("codepro", typeof(int));
    
            var supEmailParameter = supEmail != null ?
                new ObjectParameter("supEmail", supEmail) :
                new ObjectParameter("supEmail", typeof(string));
    
            var stNameParameter = stName != null ?
                new ObjectParameter("StName", stName) :
                new ObjectParameter("StName", typeof(string));
    
            var perdateParameter = perdate.HasValue ?
                new ObjectParameter("perdate", perdate) :
                new ObjectParameter("perdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upExPer", perNumParameter, codeproParameter, supEmailParameter, stNameParameter, perdateParameter);
        }
    
        public virtual int upQUExp3(Nullable<int> id, Nullable<int> perNum, Nullable<int> codepro, string supEmail, string stName, Nullable<int> quint)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var perNumParameter = perNum.HasValue ?
                new ObjectParameter("perNum", perNum) :
                new ObjectParameter("perNum", typeof(int));
    
            var codeproParameter = codepro.HasValue ?
                new ObjectParameter("codepro", codepro) :
                new ObjectParameter("codepro", typeof(int));
    
            var supEmailParameter = supEmail != null ?
                new ObjectParameter("supEmail", supEmail) :
                new ObjectParameter("supEmail", typeof(string));
    
            var stNameParameter = stName != null ?
                new ObjectParameter("StName", stName) :
                new ObjectParameter("StName", typeof(string));
    
            var quintParameter = quint.HasValue ?
                new ObjectParameter("quint", quint) :
                new ObjectParameter("quint", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upQUExp3", idParameter, perNumParameter, codeproParameter, supEmailParameter, stNameParameter, quintParameter);
        }
    
        public virtual ObjectResult<disolayPerExp_Result> disolayPerExp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<disolayPerExp_Result>("disolayPerExp");
        }
    
        public virtual ObjectResult<Nullable<int>> diffDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("diffDate");
        }
    
        public virtual ObjectResult<diffDate2_Result> diffDate2(Nullable<int> m)
        {
            var mParameter = m.HasValue ?
                new ObjectParameter("m", m) :
                new ObjectParameter("m", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<diffDate2_Result>("diffDate2", mParameter);
        }
    
        public virtual ObjectResult<Report2_Result> Report2(Nullable<System.DateTime> p)
        {
            var pParameter = p.HasValue ?
                new ObjectParameter("P", p) :
                new ObjectParameter("P", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report2_Result>("Report2", pParameter);
        }
    
        public virtual ObjectResult<Rep3_Result> Rep3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rep3_Result>("Rep3");
        }
    
        public virtual ObjectResult<RepChose_Result> RepChose(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RepChose_Result>("RepChose", nameParameter);
        }
    
        public virtual ObjectResult<Export_Result> Export()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Export_Result>("Export");
        }
    
        public virtual ObjectResult<Perview_Result> Perview()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Perview_Result>("Perview");
        }
    
        public virtual ObjectResult<string> chosecode(Nullable<int> code)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("chosecode", codeParameter);
        }
    
        public virtual int aftertrans(Nullable<int> qu, string stname, Nullable<int> code)
        {
            var quParameter = qu.HasValue ?
                new ObjectParameter("qu", qu) :
                new ObjectParameter("qu", typeof(int));
    
            var stnameParameter = stname != null ?
                new ObjectParameter("stname", stname) :
                new ObjectParameter("stname", typeof(string));
    
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("aftertrans", quParameter, stnameParameter, codeParameter);
        }
    
        public virtual ObjectResult<Ret_Result> Ret()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ret_Result>("Ret");
        }
    
        public virtual ObjectResult<Ret3_Result> Ret3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ret3_Result>("Ret3");
        }
    
        public virtual ObjectResult<Trans1_Result> Trans1(string st, Nullable<System.DateTime> from, Nullable<System.DateTime> too)
        {
            var stParameter = st != null ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(string));
    
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var tooParameter = too.HasValue ?
                new ObjectParameter("too", too) :
                new ObjectParameter("too", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Trans1_Result>("Trans1", stParameter, fromParameter, tooParameter);
        }
    
        public virtual ObjectResult<Movment_Result> Movment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Movment_Result>("Movment");
        }
    
        public virtual int Trans(string to, string p, Nullable<int> qu)
        {
            var toParameter = to != null ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(string));
    
            var pParameter = p != null ?
                new ObjectParameter("P", p) :
                new ObjectParameter("P", typeof(string));
    
            var quParameter = qu.HasValue ?
                new ObjectParameter("Qu", qu) :
                new ObjectParameter("Qu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Trans", toParameter, pParameter, quParameter);
        }
    
        public virtual ObjectResult<diffDate3_Result> diffDate3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<diffDate3_Result>("diffDate3");
        }
    }
}
